name: ctrlsend
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  app_links: 3.4.1
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  carousel_slider: 4.2.1
  cloud_firestore: 4.13.1
  cloud_firestore_platform_interface: 6.0.5
  cloud_firestore_web: 3.8.5
  cloud_functions: 4.6.0
  collection: ^1.18.0
  device_info_plus:
  dropdown_button2: 2.3.9
  equatable: 2.0.5
  firebase_core: 2.24.2
  firebase_core_platform_interface: 5.0.0
  firebase_core_web: 2.10.0
  firebase_performance: 0.9.3+8
  firebase_performance_platform_interface: 0.1.4+16
  firebase_performance_web: 0.1.4+16
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.1
  flutter_spinkit: 5.2.0
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  functions_client: 1.3.2
  go_router:
  google_fonts: 4.0.3
  google_sign_in:
  google_sign_in_android:
  google_sign_in_ios:
  google_sign_in_web: 
  gotrue: 1.12.6
  hive: 2.2.3
  intl: 0.19.0
  json_path: 0.6.2
  mime_type: 1.0.0
  onesignal_flutter: 5.2.6
  page_transition: 2.1.0
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  permission_handler:
  plugin_platform_interface: 2.1.6
  postgrest: 1.5.2
  provider: 6.0.5
  realtime_client: 1.4.0
  rxdart: 0.27.7
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  sign_in_with_apple: 4.3.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  smooth_page_indicator: 1.1.0
  sqflite: 2.2.6
  storage_client: 1.5.4
  stream_transform: 2.1.0
  supabase: 1.11.11
  supabase_flutter: 1.10.24
  timeago: 3.2.2
  url_launcher: 6.1.10
  url_launcher_android: 6.0.27
  url_launcher_ios: 6.1.4
  url_launcher_platform_interface: 2.1.2
  webview_flutter: 4.0.5
  webview_flutter_android: 3.3.1
  webview_flutter_platform_interface: 2.0.2
  webview_flutter_wkwebview: 3.1.1
  firebase_auth: ^4.16.0
  firebase_messaging: ^14.7.10

dependency_overrides:
  rxdart: 0.27.7

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 3.0.0
  image: 4.0.17
  lints: 3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
